### ISSUE TITLE
Building the guest subproject

### ISSUE THREAD

**Issue by Chocohead** [ENDERZOMBI102/MCeption#2]
I presume the [files in `libs`](https://github.com/ENDERZOMBI102/MCeption/blob/master/mception-guest/build.gradle#L19-L23) are 1.2.5 and dependencies, which Minecraft itself obviously can't be (re)distributed in the repo, is it just the remapped form using [the (intermediary?) mappings](https://github.com/ENDERZOMBI102/MCeption/blob/master/src/main/resources/mappings.tiny)? Should be easy enough to get it to download/generate them rather than needing them pre-supplied so the whole project is buildable

**Comment by ENDERZOMBI102** [comment]
yeah, but mc instead of being remapped by me, i used the one generated from the example mod (i use the intermediary jar directly, as i don't remap the sources)
its kinda a messy workflow/setup, but it does its job

for the generate things for the project, yeah, probably, but i needed it to be a fast project, so i didn't make tasks to download them and stuff, naturally the "fast project" part is out of the window right now...
